---
title: "MSD 2019 Final Project"
subtitle: "A replication and extension of hilling Effects: Online Surveillance and Wikipedia Use by Jonathon W. Penney, Berkeley Technology Law Journal"
author: "Thanaspakorn Niyomkarn, Alex Li Kong, and Sang Won Lee (tn2381, alk2225, and sl4447)"
date: '`r Sys.time()`'
output:
  pdf_document:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(wikipediatrend)

theme_set(theme_bw())

knitr::opts_chunk$set(echo = TRUE)
```

# 2. Reproducing the Original Study

```{r load data}
load("data/terrorism_data.RData")
load("data/infra_data.RData")
load("data/popular_data.RData")
```



## Total views of terrorism-related keywords before and after the incident

```{r}
terrorism_data %>%
  mutate(before_after = ifelse(date < '2013-06-01', "Before_June_2013", "After_June_2013")) %>%
  group_by(before_after) %>%
  summarise(total_views = sum(views)) %>%
  ggplot(aes(x= factor(before_after, level = c("Before_June_2013", "After_June_2013")), y=total_views, width=0.5)) +
  scale_y_continuous(name="Total Views", labels = comma) +
  xlab("Time") +
  geom_text(aes(label=comma(total_views)), vjust=-0.3, color="black", size=3.5) +
  theme_bw(base_size = 10) +
  geom_bar(stat="identity") +
  ggtitle("Total views of terrorism-related keywords before and after the incident")
```




```{r example}
lm_plot_topic <- function(input_df, gg_title){

df <- data.frame(input_df)
df <- df %>% 
  group_by(month=floor_date(date, "month")) %>%
  summarize(views=sum(views))
df$surveillence <- 'before'
df$surveillence[df$month >= '2013-06-01'] <- 'after'

model <- lm(views ~ month + surveillence + month*surveillence, data = df)
print(summary(model))


df$prediction <- predict(model, df)
df$se <- predict(model, df,
                      se.fit = TRUE)$se.fit
z.val <- qnorm(1 - (1 - 0.90)/2)
df$LoCI <- df$prediction - z.val * df$se
df$HiCI <- df$prediction + z.val * df$se

df$month <- ymd(df$month)

ggplot(df,
       aes(x = month,
           y = prediction)) +
  geom_smooth(aes(ymin = LoCI, 
                  ymax = HiCI,
                  color = surveillence),
              stat = "identity") +
  geom_point(data = df, aes(x=month, y = views)) +
  geom_vline(xintercept = as.Date('2013-06-01'), linetype = 2, colour = 'blue') +
  ylab('Views') +
  xlab('Time (monthly)') +
  scale_x_date(date_breaks = "6 month", labels = date_format("%Y-%b")) +
  scale_y_continuous(labels = comma) +
  ggtitle(gg_title)
}
```


```{r}
lm_plot_topic(terrorism_data, 'Terrorism-related keywords trend before and after June 2013')
```

```{r}
lm_plot_topic(popular_data, 'Popular keywords trend before and after June 2013')
```

```{r}
lm_plot_topic(infra_data, 'Infrastructure security-related keywords trend before and after June 2013')
```





The following is a list of all packages used to generate these results. (Leave at very end of file.)

```{r}
sessionInfo()
```